"""add student model

Revision ID: 409a402eabfa
Revises: 03ed9fe89f33
Create Date: 2023-03-07 09:50:27.737255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from models import Student


# revision identifiers, used by Alembic.
revision = '409a402eabfa'
down_revision = '03ed9fe89f33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    student1 = Student(name='Jane Doe', email='test@example.com')
    session.add(student1)
    session.commit()
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
